spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Olxmaster
    username: root
    password: password
    
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"