server:
  port: 5000
  
  spring:
     mvc:
       pathmatch:
          matching-strategy: ANT_PATH_MATCHER


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Olx
    username: root
    password: password
    
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      
